server:
  port: 8090

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://ec2-52-204-20-42.compute-1.amazonaws.com:5432/d271a4ditul6qn
    username: faqhaesmihoctz
    password: 72fdc6c54513886ac3f013360b139ed271f595bb4b8dddca2290a5a22c4a8841
